name: CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:

  checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    # outputs:
    #   checkoutcode: ${{ steps.checkout.outputs.commit }}
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v5
  
  testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run backend tests
      run: |
        cd backend
        npm install
        npm run test

    - name: Run frontend tests
      run: |
        cd frontend/ExpenzoX
        npm install
        npm run test

  deploying:
  
    name: Deploying
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: Checkout code
      uses: actions/checkout@v5    

    - name: Deploy
      run: echo "Deploying"


