name: CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:
  Application checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v5
  
  Unit Testing:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run backend tests
      run: |
        cd backend
        npm install
        npm run test

    - name: Run frontend tests
      run: |
        cd frontend/ExpenzoX
        npm install
        npm run test
  Deploying:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5    

    - name: Deploy
      run: echo "Deploying"


